### PR TITLE
WIP: Add schema for samlp addon

### PR DESCRIPTION
**Pull request by jeff-french**
Here's an attempt to add support for the Samlp addon as discussed in #31. I added the schema for it, but I don't have much experience with Golang so I'm a little lost when trying to update the CreateClient and ReadClient methods. It will need the updates to the Auth0 library contained in yieldr/go-auth0#14 Unfortunately I've reached the end of my Golang abilities so I don't know how much further I can take this PR.

### CODE REVIEW

**Comment by alexkappa** [comment]
No worries, I’ll try to get a better look and see if I can help out ;)

**Comment by rdark** [comment]
@jeff-french FWIW, I managed to get SAML configuration injected using a rule. https://auth0.com/rules/saml-attribute-mapping

**Comment by alexkappa** [comment]
Hi @jeff-french, I've continued where you left off this past couple of days. I think its almost there, but there are some minor issues with default/omitted values.

I've pushed changes to this branch: https://github.com/yieldr/terraform-provider-auth0/tree/jeff-french-improve_addons.

I can make a PR if you would like to give some feedback there.

**Comment by alexkappa** [comment]
Merged in #58, thanks for helping out with this @jeff-french!

**Pull request closed without merging**
